### PR TITLE
Responsive Navigation - IN PROGRESS

### PR DESCRIPTION
**Pull request by zsid**
Hey Joe,

I have started playing around the site and looked into making it responsive. I decided to look at the navigation since it is on every page and it is a small part. This is an initial start.

The site is not responsive as there are min-width for both navigation and footer. Once those are refactored it will start to take shape 😄 

Let me know if there is something pressing on the front-end and I can have a look at it rather than the navigation.

Let me know what you think.

Zhivko

### CODE REVIEW

**Comment by chn-challenger** [comment]
Thank you Zhivko, I will be in touch!

**Comment by chn-challenger** [comment]
Hi Zhivko,

I was thinking, if you want, you could help us do a pop up every times someone answers a question.  Telling them they got it right, earnt x number of exp points etc etc.

**Comment by zsid** [comment]
Hi Joe,

Sure, I will create a new branch from master and have a look later this week.

I haven't explored yet how to create a question and make an answer. Are there any specific steps that I need to be aware of when creating a question?

**Comment by zsid** [comment]
Hi Joe,

For the pop up a quick way will be to use bootstrap. What are your thoughts on getting the bootstrap functionality for the modal from there?

**Comment by chn-challenger** [comment]
Hi Zhivko,

I don't know enough about bootstrap to answer that, but happy to try things out. :)

**Pull request merged**
